name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "55 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: xiaozhaoqi/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 07bff390df5f1b80cda37f0eabc51e48
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
